use_directory_urls: false
# Конфігурація сайту
site_name: 'Плагін xml_ua для QGIS'
site_url: 'https://krechkivsky.github.io/xml_ua_docs/' # TODO: Замініть на ваш URL
site_author: 'Михайло Кречківський'
site_description: 'Документація для плагіна xml_ua, який спрощує роботу з кадастровими XML-файлами в QGIS.'

# Авторські права
copyright: 'Copyright &copy; 2026, krechkivsky.dev@gmail.com'

# Репозиторій
repo_url: 'https://github.com/krechkivsky/xml_ua_docs' # TODO: Замініть на URL вашого репозиторію
repo_name: 'xml_ua_docs'
edit_uri: 'edit/main/docs/' # Шлях для редагування сторінок прямо з сайту

# Тема
theme:
  name: material
  language: uk
  logo: images/logo.png
  favicon: images/icon.png
  features:
    - navigation.tabs # Навігація у вигляді вкладок
    - navigation.top # Кнопка "Нагору"
    - navigation.sections # Розділи в бічній панелі
    - search.suggest # Пропозиції при пошуку
    - search.highlight # Підсвічування результатів пошуку
    - content.code.copy # Кнопка копіювання для блоків коду
    - content.tabs.link # Посилання на конкретні вкладки в контенті
  palette:
    # Світла тема
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Перемкнути на темну тему
    # Темна тема
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Перемкнути на світлу тему

# Структура навігації
nav:
  - 'Головна': 'index.md'
  - 'Встановлення':
    - 'Встановлення QGIS': 'install_qgis.md'
    - 'Встановлення плагіна': 'install_plugin.md'
  - 'Інтерфейс':
    - 'Опис меню': 'interface_menu.md'
    - 'Опис віджету': 'interface_widget.md'
    - 'Панель шарів': 'interface_layers.md'
  - 'Створення і перевірка XML-файлів':
    - 'Перед початком роботи': 'project_crs.md'
    - 'Імпорт даних gps': 'gps_data_import.md'
    - 'Створення XML-файлів "з нуля"': 'new_xml.md'
    - 'Створення XML-файлів з шаблону': 'template2xml.md'
    - 'Зона, квартал, ділянка': 'zone_quarter.md'
    - 'Детальніше про суміжників': 'add_adjacent.md'
    - 'Робота над синтаксичними помилками': 'validation.md'
    - 'Візуальний контроль геометрії': 'visual_control.md'
    - 'Експрес контроль при відкритті файлів': 'express_control.md'
  - 'Створення документації':
    - 'Підготовка документації': 'documentation.md'
    - 'Графічні документи': 'graphic_documents.md'
    - 'Власні шаблони текстових документів': 'docx_templates.md'
  - 'Довідник':
    - 'Системи координат': 'crs.md'
    - 'Шаблони': 'templates.md'
    - 'Створні точки': 'sight_points.md'
    - 'Папка плагіна': 'plugin_folder.md'
    - 'Офлайн документація': 'https://github.com/krechkivsky/xml_ua_docs/releases/latest'
